### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by fabio1999ita** [nedalove/kLauncher#2]
Hey, can you make a english version?

**Comment by alexhyunsookang** [comment]
The translation is not difficult, but I'm not pretty sure what the developer will think.  Actually, that developer is a super lazy guy.

**Comment by alexhyunsookang** [comment]
> Hey, can you make a english version?

The translation is not difficult, but I'm not pretty sure what the developer will think. Actually, that developer is a super lazy guy.

**Comment by fabio1999ita** [comment]
> > Hey, can you make a english version?
> 
> The translation is not difficult, but I'm not pretty sure what the developer will think. Actually, that developer is a super lazy guy.

If you give me full string of korean text i can give you back full traduction

**Comment by alexhyunsookang** [comment]
> > > Hey, can you make a english version?
> > 
> > 
> > The translation is not difficult, but I'm not pretty sure what the developer will think. Actually, that developer is a super lazy guy.
> 
> If you give me full string of korean text i can give you back full traduction

I'm just a designer, maybe the developer gonna reply soon

> > > Hey, can you make a english version?
> > 
> > 
> > The translation is not difficult, but I'm not pretty sure what the developer will think. Actually, that developer is a super lazy guy.
> 
> If you give me full string of korean text i can give you back full traduction

I'm just a designer, maybe the developer gonna reply soon

**Comment by alexhyunsookang** [comment]
> > > Hey, can you make a english version?
> > 
> > 
> > The translation is not difficult, but I'm not pretty sure what the developer will think. Actually, that developer is a super lazy guy.
> 
> If you give me full string of korean text i can give you back full traduction

I'm just a designer, maybe the developer gonna reply soon

**Comment by nedalove** [comment]
> Hey, can you make a english version?

I still don't feel the need.
We will think about it when the demand for the English version increases.

**Comment by fabio1999ita** [comment]
the problem is the no korean people like me don't understand nothing...

**Comment by somersby10ml** [comment]
Oh, do foreigners use the launcher too?

**Comment by fabio1999ita** [comment]
> Oh, do foreigners use the launcher too?

lol, you posted software on github, why do you think only koreans use it?

**Comment by alexhyunsookang** [comment]
> > Oh, do foreigners use the launcher too?
> 
> lol, you posted software on github, why do you think only koreans use it?

Oh, I feel like he will give me a lot of work soon.

**Comment by fabio1999ita** [comment]
> > > > Hey, can you make a english version?
> > > 
> > > 
> > > The translation is not difficult, but I'm not pretty sure what the developer will think. Actually, that developer is a super lazy guy.
> > 
> > 
> > If you give me full string of korean text i can give you back full traduction
> 
> You can try to use programs to extract text from windows. What I'm currently using is [Textify](https://rammichael.com/textify) and [WinCheat](http://alinconstantin.dynu.com/Download/WinCheat/), but [here ](https://alternativeto.net/software/textify/)you can find a lot of alternatives to it.
> 
> The same as you, I tried translating wLauncher in the past (the version for SC:R) using Textify, but I had encountered some errors in the program I was using to compile the disassembled exe and I gave up because all the people I knew weren't interested by it. By the time I gave up, I knew what every setting did, so I didn't feel to look up on how to sort out those errors, since it was already only for myself at that point.

the complete translation had been done in the Wlauncher and everything was more intuitive, here is not intuitive and the problem is not uderstand korean but also compatibility whit system like:
![image](https://user-images.githubusercontent.com/27001568/132947944-97682f3f-cfd3-4419-b1c1-1ec60566a4bf.png)
it say: cannon find that file, if i go inside the main directory:
![image](https://user-images.githubusercontent.com/27001568/132947973-b8cbb8b3-8fde-418b-ac90-f20cf3651baa.png)
or also when i start starcraft whit official launcher:
![image](https://user-images.githubusercontent.com/27001568/132947987-531d7c10-cbdf-4d32-9d16-2b8d754bac6e.png)

**Comment by CanYouJustWorkPlease** [comment]
> > > > > Hey, can you make a english version?
> > > > 
> > > > 
> > > > The translation is not difficult, but I'm not pretty sure what the developer will think. Actually, that developer is a super lazy guy.
> > > 
> > > 
> > > If you give me full string of korean text i can give you back full traduction
> > 
> > 
> > You can try to use programs to extract text from windows. What I'm currently using is [Textify](https://rammichael.com/textify) and [WinCheat](http://alinconstantin.dynu.com/Download/WinCheat/), but [here ](https://alternativeto.net/software/textify/)you can find a lot of alternatives to it.
> > The same as you, I tried translating wLauncher in the past (the version for SC:R) using Textify, but I had encountered some errors in the program I was using to compile the disassembled exe and I gave up because all the people I knew weren't interested by it. By the time I gave up, I knew what every setting did, so I didn't feel to look up on how to sort out those errors, since it was already only for myself at that point.
> 
> the complete translation had been done in the Wlauncher and everything was more intuitive, here is not intuitive and the problem is not only uderstand korean but also compatibility whit system like:
> ![image](https://user-images.githubusercontent.com/27001568/132947944-97682f3f-cfd3-4419-b1c1-1ec60566a4bf.png)
> it says: cannon find that file, if i go inside the main directory:
> ![image](https://user-images.githubusercontent.com/27001568/132947973-b8cbb8b3-8fde-418b-ac90-f20cf3651baa.png)
> or also when i start starcraft whit official launcher:
> ![image](https://user-images.githubusercontent.com/27001568/132947987-531d7c10-cbdf-4d32-9d16-2b8d754bac6e.png)

Hmm. Maybe changing the system wide language from italian to korean would make the program to run.
I'd help you out testing that, but unfortunately I'm not running Windows 10, because it seems kLauncher works only on Windows 10.

**Comment by fabio1999ita** [comment]
klauncher works if i start starcraft from klauncher, it doesn't work if i start starcraft from battle.net, i get last error that i sent but i can't read the korean message

**Comment by CanYouJustWorkPlease** [comment]
> klauncher works if i start starcraft from klauncher, it doesn't work if i start starcraft from [battle.net](http://battle.net), i get last error that i sent but i can't read the korean message

Can you extract the error message from the window below by either using Textify or by selecting the error message window and hitting CTRL + C, then opening a text file and hitting CTRL + V:
![132947987-531d7c10-cbdf-4d32-9d16-2b8d754bac6e](https://user-images.githubusercontent.com/73692469/132974225-34b125bf-6bc1-464d-97e1-d27d4e772af7.png)

Can you thereafter paste the extracted text here, maybe I can decode it?

**Comment by fabio1999ita** [comment]
---------------------------
¾Ë¸²
---------------------------
·±Ã³ ½ÇÇà ½ÇÆÐ (½ºÅ¸Å©·¡ÇÁÆ®¸¦ °ü¸®ÀÚ ±ÇÇÑÀ¸·Î ½ÇÇà ÇØÁÖ¼¼¿ä)
---------------------------
OK   
---------------------------

**Comment by CanYouJustWorkPlease** [comment]
That's nice! Also thanks! 

Is there a guide on how to do that for Notepad++?

I managed to decode it using [this](https://www.iosart.com/tools/charset-fixer/?source-text=%C2%BE%C3%8B%C2%B8%C2%B2%0D%0A%C2%B7%C2%B1%C3%83%C2%B3+%C2%BD%C3%87%C3%87%C3%A0+%C2%BD%C3%87%C3%86%C3%90+%28%C2%BD%C2%BA%C3%85%C2%B8%C3%85%C2%A9%C2%B7%C2%A1%C3%87%C3%81%C3%86%C2%AE%C2%B8%C2%A6+%C2%B0%C3%BC%C2%B8%C2%AE%C3%80%C3%9A+%C2%B1%C3%87%C3%87%C3%91%C3%80%C2%B8%C2%B7%C3%8E+%C2%BD%C3%87%C3%87%C3%A0+%C3%87%C3%98%C3%81%C3%96%C2%BC%C2%BC%C2%BF%C3%A4%29&input-encoding=EUC-KR) site called:

https://www.iosart.com/tools/charset-fixer/

, and picking Korean (EUC-KR).

In the past I used this site to decode, but this time I had no luck:

https://r12a.github.io/app-encodings/

Did you try to extract the text within kLauncher using Textify?

**Comment by fabio1999ita** [comment]
no, i'm not test textify

**Comment by fabio1999ita** [comment]
any news for traduction?
