### ISSUE TITLE
know who is lagger

### ISSUE THREAD

**Issue by fabio1999ita** [nedalove/kLauncher#3]
is possible to know who is lagger inside the game? i see only ping in blue or red

**Comment by nedalove** [comment]
![image](https://user-images.githubusercontent.com/57429138/133109644-485768c7-04d0-46e8-80ba-6c320456596f.png)

-InGame
Keypad .

-Lobby
Auto

**Comment by fabio1999ita** [comment]
> ![image](https://user-images.githubusercontent.com/57429138/133109644-485768c7-04d0-46e8-80ba-6c320456596f.png)
> 
> -InGame
> Keypad .
> 
> -Lobby
> Auto
> 
> 핑 = Ping

really in game key are "ctrl + O", but that is just ping, you don't know if player lag, not always if player have high ping = lag

**Comment by nedalove** [comment]
> > ![영상](https://user-images.githubusercontent.com/57429138/133109644-485768c7-04d0-46e8-80ba-6c320456596f.png)
> > - 게임 내 
> > 키패드 .
> > -로비 
> > 자동
> > 핑 = 핑
> 
> 실제로 게임 키는 "ctrl + O"이지만 그것은 단지 핑입니다. 플레이어가 지연되는지 여부를 알 수 없습니다. 플레이어가 높은 핑 = 지연을 가지고 있으면 항상 그런 것은 아닙니다.

There are many causes of lag, and the biggest one is ping. It's difficult to get 100% perfect lag in the current game.

**Comment by fabio1999ita** [comment]
> There are many causes of lag, and the biggest one is ping. It's difficult to get 100% perfect lag in the current game.
> If there is a more certain way, I'll think about it.

i think also the ping often is not correct, i often notice that even if the ping is good there is lag
i remeber that klaucher say whit a red writing who was lagger

**Comment by fabio1999ita** [comment]
do you add functionality or just close?

**Comment by nedalove** [comment]
> do you add functionality or just close?

The repository has changed.
https://github.com/kLauncher/kLauncher/releases
Are there any bugs about lag now?
