### ISSUE TITLE
klaucher break COD Warzone game

### ISSUE THREAD

**Issue by fabio1999ita** [nedalove/kLauncher#4]
this happend when i launch the klaucher then starcraft, after i close all i can't launch warzone game
if i close and reopen the battle.net launcher warzone start but crash after 10-15 second only way to fix crash is reboot pc
what process the klaucher generate? i mean name of process

**Comment by somersby10ml** [comment]
Quit both Blizzard Launcher and K Launcher, then turn on Blizzard Launcher again and start Warzone.

**Comment by fabio1999ita** [comment]
> Quit both Blizzard Launcher and K Launcher, then turn on Blizzard Launcher again and start Warzone.

only way is reboot pc

**Comment by nedalove** [comment]
> > Quit both Blizzard Launcher and K Launcher, then turn on Blizzard Launcher again and start Warzone.
> 
> only way is reboot pc

Try the latest version Still having the same problem?

**Comment by fabio1999ita** [comment]
no, after klaucher inject to starcraft warzone crash after 10-15 seconds after i start it
